image: gitpod/workspace-full

tasks:
  - name: Install Backend Dependencies
    command: pip install -r backend/requirements.txt

  - name: Install Frontend Dependencies
    command: cd frontend && npm install

  - name: Start Backend
    command: cd backend && pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  - name: Start Frontend
    command: cd frontend && npm install && npm run dev

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5173
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
