image: gitpod/workspace-full

tasks:
  - name: Install Backend Dependencies
    command: pip install -r backend/requirements.txt

  - name: Install Frontend Dependencies
    command: cd frontend && npm install

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5173
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
